[mypy]
mypy_path = workflow/scripts:workflow/sql_storage_plugin
python_version = 3.10

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-snakemake_interface_storage_plugins.*]
ignore_missing_imports = True
